# Generated by Django 5.2.1 on 2025-09-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.product'),
        ),
    ]
