# Generated by Django 5.2.1 on 2025-09-28 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=50)),
                ('delivery_to_name', models.CharField(max_length=255)),
                ('delivery_to_address', models.TextField()),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='notes',
            new_name='terms',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='reference',
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='ship_to_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ship_to_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quotationlineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryNoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicemgmt.deliverynote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.product')),
            ],
        ),
    ]
