# Generated by Django 5.2.1 on 2025-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0002_alter_invoicelineitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
