# Generated by Django 5.2.1 on 2025-09-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0002_deliverynote_rename_notes_quotation_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynotelineitem',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='deliverynotelineitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='purchaselineitem',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='customer',
        ),
        migrations.DeleteModel(
            name='DeliveryNote',
        ),
        migrations.DeleteModel(
            name='DeliveryNoteLineItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationLineItem',
        ),
        migrations.DeleteModel(
            name='RecurringInvoice',
        ),
    ]
