# Generated by Django 5.2.1 on 2025-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0003_remove_invoicelineitem_line_total_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('paid', 'Paid')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
    ]
