# Generated by Django 5.2.1 on 2025-09-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0003_remove_deliverynotelineitem_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Note'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='do_date',
            field=models.DateField(blank=True, null=True, verbose_name='D.O. Date'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='P.O. Date'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='P.O. Number'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ship_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ship To'),
        ),
    ]
