# Generated by Django 5.2.1 on 2025-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0003_purchase_purchase_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselineitem',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaselineitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='purchaselineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
