# Generated by Django 5.2.1 on 2025-09-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0004_purchase_delivery_note_purchase_do_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='do_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='po_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ship_to',
        ),
    ]
