# Generated by Django 5.2.1 on 2025-09-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0004_remove_purchaselineitem_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselineitem',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoicemgmt.purchase'),
            preserve_default=False,
        ),
    ]
