# Generated by Django 5.2.1 on 2025-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, choices=[('United States', 'United States'), ('India', 'India'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('UAE', 'UAE')], max_length=100, null=True),
        ),
    ]
