# Generated by Django 5.2.1 on 2025-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0006_alter_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
