# Generated by Django 5.2.1 on 2025-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0006_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='special_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
