# Generated by Django 5.2.1 on 2025-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0007_invoice_special_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='special_discount',
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
