# Generated by Django 5.2.1 on 2025-06-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0008_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=10)),
                ('next_due_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.product')),
            ],
        ),
    ]
