# Generated by Django 5.2.1 on 2025-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0008_remove_invoice_special_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, default='30 days credit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
