# Generated by Django 5.2.1 on 2025-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0009_alter_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
