# Generated by Django 5.2.1 on 2025-10-03 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0010_alter_invoicelineitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=50)),
                ('delivery_to_name', models.CharField(max_length=255)),
                ('delivery_to_address', models.TextField()),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicemgmt.deliverynote')),
            ],
        ),
    ]
