# Generated by Django 5.2.1 on 2025-06-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0010_product_quantity_in_stock_product_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.product'),
        ),
    ]
