# Generated by Django 5.2.1 on 2025-10-03 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0011_deliverynote_deliverynotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_note_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
