# Generated by Django 5.2.1 on 2025-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0012_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_rate',
        ),
    ]
