# Generated by Django 5.2.1 on 2025-10-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0012_deliverynote_delivery_note_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
