# Generated by Django 5.2.1 on 2025-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0013_alter_invoicelineitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
