# Generated by Django 5.2.1 on 2025-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0014_alter_invoicelineitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
