# Generated by Django 5.2.1 on 2025-10-13 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0015_alter_purchase_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
