# Generated by Django 5.2.1 on 2025-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0015_remove_product_quantity_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
