# Generated by Django 5.2.1 on 2025-10-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0016_alter_purchase_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
