# Generated by Django 5.2.1 on 2025-10-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0017_alter_purchaselineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynotelineitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynotelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
