# Generated by Django 5.2.1 on 2025-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0018_deliverynotelineitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynotelineitem',
            name='complete',
            field=models.BooleanField(blank=True),
        ),
    ]
