# Generated by Django 5.2.1 on 2025-10-16 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0019_alter_deliverynotelineitem_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
