# Generated by Django 5.2.1 on 2025-10-30 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0019_alter_deliverynotelineitem_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
