# Generated by Django 5.2.1 on 2025-06-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0020_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
