# Generated by Django 5.2.1 on 2025-10-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0020_product_alter_deliverynote_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='description_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_fk_items', to='invoicemgmt.product'),
        ),
    ]
