# Generated by Django 5.2.1 on 2025-11-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0021_invoicelineitem_description_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='company_email',
        ),
    ]
