# Generated by Django 5.2.1 on 2025-11-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0022_remove_deliverynote_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(),
        ),
    ]
