# Generated by Django 5.2.1 on 2025-11-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0023_alter_deliverynote_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='signature_date',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='terms',
        ),
    ]
