# Generated by Django 5.2.1 on 2025-11-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0024_remove_deliverynote_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_to_fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_to_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='lpo_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_value', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicemgmt.deliverynote')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryNoteLineItem',
        ),
    ]
