# Generated by Django 5.2.1 on 2025-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0024_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
