# Generated by Django 5.2.1 on 2025-11-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0025_deliverynote_delivery_to_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('merged', 'Merged')], default='open', max_length=10),
        ),
    ]
