# Generated by Django 5.2.1 on 2025-11-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0026_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='purchase_attachments/'),
        ),
    ]
