# Generated by Django 5.2.1 on 2025-06-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0026_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='TEMP', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
