# Generated by Django 5.2.1 on 2025-07-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0029_shop_invoice_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicemgmt.shop'),
        ),
    ]
