# Generated by Django 5.2.1 on 2025-11-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0029_quotationlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoice_attachments/'),
        ),
    ]
