# Generated by Django 5.2.1 on 2025-07-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0030_alter_invoice_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
