# Generated by Django 5.2.1 on 2025-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0034_purchaselineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
