# Generated by Django 5.2.1 on 2025-08-01 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0037_quotation_quotationlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
    ]
